name: manual

on:
  workflow_dispatch:
    inputs:
      upstream_tag:
        description: Upstream tag to build
        required: true
        default: latest
      upstream_validator_image:
        description: Upstream validator image to use
        required: true
        default: gcr.io/prysmaticlabs/prysm/validator
      upstream_beacon_image:
        description: Upstream beacon image to use
        required: true
        default: gcr.io/prysmaticlabs/prysm/beacon
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            samcm/prysm-debian
          tags: |
            type=raw,value=${{ inputs.upstream_tag }}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull latest
        run: >
          docker pull ${{ inputs.upstream_beacon_image }}:${{ inputs.upstream_tag }};
          docker pull ${{ inputs.upstream_validator_image}}:${{ inputs.upstream_tag }};
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            tag=${{ inputs.upstream_tag }}
            beacon=${{ inputs.upstream_beacon_image }}
            validator=${{ inputs.upstream_validator_image }}
